on:
  workflow_dispatch:
  push:
    branches: [ main ]

name: Quarto Publish

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto CLI
        uses: quarto-dev/quarto-actions/setup-quarto@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Restore renv (if you use renv)
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render site
        run: quarto render

      - name: Show _site (debug)
        run: |
          echo "Contenido de _site:"
          ls -la _site || true

      - name: Publish to gh-pages (Quarto action)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}